##### importing libraries 

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [2]:
training=pd.read_csv("0000000000002429_training_titanic_x_y_train (4).csv")
testing=pd.read_csv("0000000000002429_test_titanic_x_test.csv")

In [3]:
training.head(10)

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   
5       3                      Lemberopolous, Mr. Peter L    male  34.5   
6       1    Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
7       3                              Jonkoff, Mr. Lalio    male  23.0   
8       2                    Williams, Mr. Charles Eugene    male   NaN   
9       3                        Rouse, Mr. Richard Henry    male  50.0   

   SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0      1      0           228414  26.0000   NaN        S         1  
1      0      0         A/5 2466   8.0500   NaN        S         0  
2      0      0           250655  26.0000   NaN        S         0  
3      0      4           349909  21.0750   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
5      0      0             2683   6.4375   NaN        C         0  
6      1      0           113803  53.1000  C123        S         1  
7      0      0           349204   7.8958   NaN        S         0  
8      0      0           244373  13.0000   NaN        S         1  
9      0      0         A/5 3594   8.0500   NaN        S         0

#### Data Preprocessing

In [4]:
title_training=[]
for i in training['Name']:
    title_training.append(i.split(',')[1].split('.')[0].strip())

In [5]:
x=training["Name"][0]
x

'Weisz, Mrs. Leopold (Mathilde Francoise Pede)'

In [6]:
def fun(name):
    if "Master" in name:
        return 0
    elif "Miss" in name:
        return 1
    elif "Mrs" in name:
        return 2
    elif "Mr" in name:
        return 3
    else:
        return 4
x=training["Name"].apply(fun)

In [7]:
title_training=np.array(x)

In [8]:
title_training

array([2, 3, 3, 2, 3, 3, 2, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 1, 4, 2,
       2, 3, 2, 1, 3, 3, 3, 3, 2, 3, 3, 1, 4, 3, 0, 0, 3, 3, 3, 3, 2, 1,
       3, 3, 3, 3, 2, 3, 1, 0, 3, 2, 3, 1, 3, 3, 3, 2, 3, 3, 3, 2, 1, 2,
       3, 3, 3, 3, 2, 3, 3, 3, 3, 1, 1, 2, 2, 2, 2, 3, 2, 3, 1, 3, 3, 3,
       3, 3, 2, 2, 1, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3,
       1, 2, 3, 1, 3, 3, 3, 3, 1, 1, 2, 4, 1, 1, 1, 3, 3, 3, 3, 2, 3, 1,
       3, 3, 3, 2, 3, 3, 3, 4, 3, 2, 3, 3, 3, 3, 2, 3, 1, 1, 2, 3, 2, 1,
       2, 3, 2, 3, 1, 2, 2, 1, 3, 3, 3, 2, 3, 3, 3, 0, 3, 4, 2, 3, 4, 1,
       2, 3, 3, 3, 3, 1, 2, 3, 2, 0, 3, 1, 2, 3, 3, 1, 1, 3, 3, 3, 3, 3,
       3, 3, 1, 4, 1, 3, 1, 3, 2, 3, 3, 0, 2, 2, 1, 3, 1, 3, 3, 0, 1, 1,
       1, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 0, 2, 3, 3, 3, 3, 2, 3, 1, 3, 3,
       3, 2, 3, 3, 1, 2, 1, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 2, 3, 3, 4,
       3, 3, 2, 3, 3, 3, 0, 0, 3, 2, 1, 3, 3, 0, 3, 3, 3, 2, 1, 3, 3, 1,
       1, 3, 3, 3, 1, 3, 3, 1, 2, 1, 0, 3, 3, 1, 3,

In [9]:
testing.head(10)

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   
5       1                            Artagaveytia, Mr. Ramon    male  71.0   
6       3                          de Pelsmaeker, Mr. Alfons    male  16.0   
7       3                                 Scanlan, Mr. James    male   NaN   
8       3                    Pettersson, Miss. Ellen Natalia  female  18.0   
9       3                                Smiljanic, Mr. Mile    male   NaN   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S  
5      0      0    PC 17609  49.5042   NaN        C  
6      0      0      345778   9.5000   NaN        S  
7      0      0       36209   7.7250   NaN        Q  
8      0      0      347087   7.7750   NaN        S  
9      0      0      315037   8.6625   NaN        S

In [10]:
title_testing=np.array(testing["Name"].apply(fun))

In [11]:
title_testing

array([0, 4, 3, 2, 3, 3, 3, 3, 1, 3, 1, 3, 1, 1, 3, 3, 3, 0, 3, 1, 1, 3,
       1, 1, 3, 3, 3, 3, 1, 1, 3, 3, 3, 3, 3, 2, 1, 3, 3, 3, 1, 3, 4, 3,
       1, 0, 3, 1, 3, 3, 3, 1, 2, 1, 3, 3, 0, 3, 3, 3, 3, 4, 2, 1, 2, 3,
       3, 4, 1, 4, 3, 3, 3, 3, 3, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 3, 1, 3, 3, 1, 3, 3, 3, 3, 0, 1, 1, 3, 1, 0, 1, 1, 4, 4, 3, 3,
       3, 2, 2, 3, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 2, 1, 3, 1, 3,
       1, 3, 3, 1, 3, 0, 3, 1, 2, 1, 1, 3, 3, 3, 2, 1, 2, 1, 1, 3, 1, 3,
       3, 3, 3, 1, 3, 3, 0, 1, 2, 3, 2, 3, 1, 3, 3, 3, 2, 3, 3, 1, 1, 1,
       2, 4, 3, 4, 3, 3, 3, 3, 3, 3, 2, 1, 3, 1, 3, 3, 1, 1, 3, 3, 3, 4,
       2, 3, 3], dtype=int64)

In [12]:
training.describe(include="all")

Pclass                                           Name   Sex  \
count   668.000000                                            668   668   
unique         NaN                                            668     2   
top            NaN  Weisz, Mrs. Leopold (Mathilde Francoise Pede)  male   
freq           NaN                                              1   427   
mean      2.296407                                            NaN   NaN   
std       0.831638                                            NaN   NaN   
min       1.000000                                            NaN   NaN   
25%       2.000000                                            NaN   NaN   
50%       3.000000                                            NaN   NaN   
75%       3.000000                                            NaN   NaN   
max       3.000000                                            NaN   NaN   

               Age       SibSp       Parch Ticket        Fare Cabin Embarked  \
count   536.000000  668.000000  668.000000    668  668.000000   154      667   
unique         NaN         NaN         NaN    524         NaN   119        3   
top            NaN         NaN         NaN   1601         NaN    G6        S   
freq           NaN         NaN         NaN      6         NaN     4      484   
mean     29.700560    0.528443    0.407186    NaN   32.064552   NaN      NaN   
std      14.240257    1.080327    0.854695    NaN   45.320835   NaN      NaN   
min       0.670000    0.000000    0.000000    NaN    0.000000   NaN      NaN   
25%      21.000000    0.000000    0.000000    NaN    7.925000   NaN      NaN   
50%      29.000000    0.000000    0.000000    NaN   14.750000   NaN      NaN   
75%      38.250000    1.000000    0.000000    NaN   31.275000   NaN      NaN   
max      80.000000    8.000000    6.000000    NaN  512.329200   NaN      NaN   

          Survived  
count   668.000000  
unique         NaN  
top            NaN  
freq           NaN  
mean      0.402695  
std       0.490808  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [13]:
testing.describe(include='all')

Pclass                            Name   Sex         Age  \
count   223.000000                             223   223  178.000000   
unique         NaN                             223     2         NaN   
top            NaN  Davies, Master. John Morgan Jr  male         NaN   
freq           NaN                               1   150         NaN   
mean      2.345291                             NaN   NaN   29.694775   
std       0.850047                             NaN   NaN   15.398053   
min       1.000000                             NaN   NaN    0.420000   
25%       2.000000                             NaN   NaN   19.250000   
50%       3.000000                             NaN   NaN   27.000000   
75%       3.000000                             NaN   NaN   37.750000   
max       3.000000                             NaN   NaN   71.000000   

             SibSp       Parch   Ticket        Fare    Cabin Embarked  
count   223.000000  223.000000      223  223.000000       50      222  
unique         NaN         NaN      212         NaN       49        3  
top            NaN         NaN  CA 2144         NaN  B58 B60        S  
freq           NaN         NaN        3         NaN        2      160  
mean      0.506726    0.304933      NaN   32.622551      NaN      NaN  
std       1.169700    0.634108      NaN   61.062047      NaN      NaN  
min       0.000000    0.000000      NaN    0.000000      NaN      NaN  
25%       0.000000    0.000000      NaN    7.879200      NaN      NaN  
50%       0.000000    0.000000      NaN   12.475000      NaN      NaN  
75%       1.000000    0.000000      NaN   30.035400      NaN      NaN  
max       8.000000    2.000000      NaN  512.329200      NaN      NaN

In [14]:
tr=training.drop("Name",axis=1)
def gender(sex):
    if sex =="female":
        return 0
    else:
        return 1
tr["Sex"]=tr["Sex"].apply(gender)

In [15]:
tr.head()

Pclass  Sex   Age  SibSp  Parch           Ticket    Fare Cabin Embarked  \
0       2    0  29.0      1      0           228414  26.000   NaN        S   
1       3    1   NaN      0      0         A/5 2466   8.050   NaN        S   
2       2    1  39.0      0      0           250655  26.000   NaN        S   
3       3    0  29.0      0      4           349909  21.075   NaN        S   
4       3    1  25.0      0      0  SOTON/OQ 392076   7.050   NaN        S   

   Survived  
0         1  
1         0  
2         0  
3         0  
4         0

In [16]:
tr.loc[tr['Embarked'].isnull(), 'Embarked']='S'
tr.loc[tr['Embarked']=='S', 'Embarked']=1
tr.loc[tr['Embarked']=='C', 'Embarked']=2
tr.loc[tr['Embarked']=='Q', 'Embarked']=3
tr.head()

Pclass  Sex   Age  SibSp  Parch           Ticket    Fare Cabin Embarked  \
0       2    0  29.0      1      0           228414  26.000   NaN        1   
1       3    1   NaN      0      0         A/5 2466   8.050   NaN        1   
2       2    1  39.0      0      0           250655  26.000   NaN        1   
3       3    0  29.0      0      4           349909  21.075   NaN        1   
4       3    1  25.0      0      0  SOTON/OQ 392076   7.050   NaN        1   

   Survived  
0         1  
1         0  
2         0  
3         0  
4         0

In [17]:
tr.loc[tr['Age'].isnull(), 'Age']=tr.loc[tr['Age'].notnull() , 'Age'].median()
tr.loc[tr['Cabin'].isnull(), 'Cabin']=0
tr.loc[tr['Cabin']!=0, 'Cabin']=1
tr=tr.drop('Ticket', axis=1)
tr.head()

Pclass  Sex   Age  SibSp  Parch    Fare Cabin Embarked  Survived
0       2    0  29.0      1      0  26.000     0        1         1
1       3    1  29.0      0      0   8.050     0        1         0
2       2    1  39.0      0      0  26.000     0        1         0
3       3    0  29.0      0      4  21.075     0        1         0
4       3    1  25.0      0      0   7.050     0        1         0

In [18]:
training_data=tr.values
x=training_data[:, :-1]
y=training_data[:, -1]

In [19]:
x=np.append(x, title_training.reshape(-1, 1), axis=1)
x.shape

(668, 9)

In [20]:
y=y.astype('int')
y.shape

(668,)

In [21]:
ts=testing
ts=ts.drop('Name', axis=1)
ts['Sex']=ts["Sex"].apply(gender)
ts.loc[ts['Age'].isnull(), 'Age']=ts.loc[ts['Age'].notnull() , 'Age'].median()
ts.loc[ts['Embarked'].isnull(), 'Embarked']='S'
ts.loc[ts['Embarked']=='S', 'Embarked']=1
ts.loc[ts['Embarked']=='C', 'Embarked']=2
ts.loc[ts['Embarked']=='Q', 'Embarked']=3
ts.loc[ts['Cabin'].isnull(), 'Cabin']=0
ts.loc[ts['Cabin']!=0, 'Cabin']=1
ts=ts.drop('Ticket', axis=1)
testing_data=ts.values
testing_data=np.append(testing_data, title_testing.reshape(-1, 1), axis=1)
testing_data.shape

(223, 9)

In [22]:
testing_data[:8,]

array([[2, 1, 8.0, 1, 1, 36.75, 0, 1, 0],
       [1, 0, 49.0, 0, 0, 25.9292, 1, 1, 4],
       [3, 1, 27.0, 0, 0, 7.7375, 0, 3, 3],
       [2, 0, 24.0, 2, 1, 27.0, 0, 1, 2],
       [1, 1, 36.0, 0, 0, 26.2875, 1, 1, 3],
       [1, 1, 71.0, 0, 0, 49.5042, 0, 2, 3],
       [3, 1, 16.0, 0, 0, 9.5, 0, 1, 3],
       [3, 1, 27.0, 0, 0, 7.725, 0, 3, 3]], dtype=object)

In [23]:
training_data

array([[2, 0, 29.0, ..., 0, 1, 1],
       [3, 1, 29.0, ..., 0, 1, 0],
       [2, 1, 39.0, ..., 0, 1, 0],
       ...,
       [3, 1, 32.0, ..., 0, 1, 1],
       [3, 0, 22.0, ..., 0, 1, 0],
       [3, 0, 29.0, ..., 0, 3, 1]], dtype=object)

In [24]:
x_train,x_test,y_train,y_test= model_selection.train_test_split(x,y,test_size=0.2,random_state=0)

##### Logistic Regression 

In [25]:
clf_lr=LogisticRegression(max_iter=1000)

In [26]:
clf_lr.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [27]:
y_pred_lr=clf_lr.predict(x_test)

In [28]:
clf_lr.score(x_train,y_train)

0.799625468164794

In [29]:
clf_lr.score(x_test,y_test)

0.8283582089552238

##### Random Forest Classifier 

In [30]:
rfc=RandomForestClassifier()

In [31]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [32]:
rfc.score(x_train,y_train)

0.9887640449438202

In [33]:
rfc.score(x_test,y_test)

0.8059701492537313

#### Randomized Search Cv 

In [34]:
from sklearn.model_selection import RandomizedSearchCV

In [35]:
parameters = {
              'penalty':['l1', 'l2', 'elasticnet', 'none'],
              'C':[0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0],
              'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
              }

In [36]:
rsc=RandomizedSearchCV(clf_lr,parameters)

In [37]:
import warnings
warnings.filterwarnings("ignore")
rsc.fit(x,y)

RandomizedSearchCV(estimator=LogisticRegression(max_iter=1000),
                   param_distributions={'C': [0.25, 0.5, 0.75, 1.0, 1.25, 1.5,
                                              1.75, 2.0],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']})

In [38]:
rsc.best_params_

{'solver': 'lbfgs', 'penalty': 'none', 'C': 1.5}

#### LogisticRegression with best params 

In [39]:
clf=LogisticRegression(solver= 'newton-cg', penalty= 'none', C= 0.5)

In [40]:
clf.fit(x,y)

LogisticRegression(C=0.5, penalty='none', solver='newton-cg')

In [41]:
y_pred=clf.predict(testing_data)

In [42]:
y_test

array([1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1])

In [43]:
np.savetxt(X=y_pred, delimiter=',', fname='predicted_tita.csv', fmt='%.0f')